import type { Metadata } from "next";
import { FunnelDisplay } from "@ndk/ui/next-fonts";
import "./globals.css";
import { ThemeProvider } from "@ndk/ui/contexts/theme-provider";
import "@ndk/ui/themes/neutral.css";
import "@ndk/ui/tokens.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${FunnelDisplay.className}`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
